services:
  - type: web
    name: bugteasers
    env: node
    plan: free
    repo: https://github.com/jidnyesh12/bugteasers.git
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    rootDir: server